### ISSUE TITLE
how to set layoutmanager in androidx??

### ISSUE THREAD

**Issue by jainsanket77** [cdflynn/turn-layout-manager#4]
setLayoutManager(androidx.recyclerview.widget.RecyclerView.LayoutManager) in RecyclerView cannot be applied
to
(cdflynn.android.library.turn.TurnLayoutManager)
getting error

what i am do??

**Comment by cdflynn** [comment]
This is because `androidx` changed the namespace of `LayoutManager` (and everything else in the support libraries).  Once `androidx` is out of alpha I can migrate `TurnLayoutManager` to `androidx`.

In the meantime if you absolutely need to use the alpha `androidx`, you can either submit a PR here or fork and migrate it.
